# Generated by Django 6.0 on 2025-12-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
