# Generated by Django 6.0 on 2025-12-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_clinicuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicuser',
            name='username',
        ),
    ]
