# Generated by Django 6.0 on 2025-12-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_prescription_prescriptionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='procedure_type',
            field=models.CharField(blank=True, choices=[('Teeth Cleaning', 'Teeth Cleaning'), ('Filling', 'Filling'), ('Implant', 'Implant'), ('Consultation', 'Consultation'), ('Root Canal Treatment', 'Root Canal Treatment'), ('Checkup', 'Checkup'), ('Veneers', 'Veneers'), ('Ortho Consult', 'Ortho Consult'), ('Braces Adj.', 'Braces Adj.'), ('Surgery', 'Surgery')], max_length=50, null=True),
        ),
    ]
