# Generated by Django 6.0 on 2025-12-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_appointment_phone_number_appointment_procedure_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Awaiting', 'Checked In'])), fields=('doctor', 'date', 'time'), name='unique_doctor_time_slot'),
        ),
    ]
