# Generated by Django 6.0 on 2025-12-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_appointment_unique_doctor_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicpatient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicpatient',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='clinicpatient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clinicpatient',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clinicpatient',
            name='medical_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
