# Generated by Django 6.0 on 2025-12-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_clinicpatient_address_clinicpatient_blood_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrescriptionItem',
        ),
    ]
