# Generated by Django 6.0 on 2025-12-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='updated_at',
        ),
    ]
