# Generated by Django 6.0 on 2025-12-25 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stockitem_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='supplier',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='has_expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='image',
            field=models.ImageField(upload_to='stock_images/'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockitem')),
            ],
        ),
    ]
