# Generated by Django 6.0 on 2025-12-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stockitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
