# Generated by Django 6.0 on 2025-12-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stockitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='price',
        ),
    ]
