# Generated by Django 6.0 on 2025-12-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_stockentry_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='category',
            field=models.CharField(choices=[('Medications', 'Medications'), ('Supplies', 'Supplies'), ('Equipment', 'Equipment'), ('Vaccines', 'Vaccines'), ('Others', 'Others'), ('Consumables', 'Consumables'), ('Personal Protective Equipment', 'Personal Protective Equipment')], max_length=100),
        ),
    ]
