# Generated by Django 6.0 on 2025-12-28 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_prescriptionitem'),
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationrecord',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='examinationrecord',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='examinationrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examination', to='api.appointment')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='api.clinicpatient')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='examination',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='medical_records.examination'),
        ),
        migrations.CreateModel(
            name='ToothExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.PositiveSmallIntegerField()),
                ('pocket_depth', models.JSONField(default=list)),
                ('bleeding', models.JSONField(default=list)),
                ('mobility', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('selected_surfaces', models.JSONField(blank=True, null=True)),
                ('clinical_note', models.TextField(blank=True, null=True)),
                ('soap_notes', models.JSONField(blank=True, null=True)),
                ('procedure_history', models.JSONField(default=list)),
                ('timeline_history', models.JSONField(default=list)),
                ('removal_history', models.JSONField(default=list)),
                ('tooth_shade', models.CharField(blank=True, max_length=10, null=True)),
                ('last_cleaned', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth', to='medical_records.examination')),
            ],
            options={
                'unique_together': {('examination', 'tooth_number')},
            },
        ),
        migrations.DeleteModel(
            name='ExaminationProgress',
        ),
        migrations.DeleteModel(
            name='ExaminationRecord',
        ),
    ]
