# Generated by Django 6.0 on 2025-12-28 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_prescriptionitem'),
        ('medical_records', '0002_remove_examinationrecord_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_prescriptions', to='api.appointment'),
        ),
    ]
