# Generated by Django 6.0 on 2025-12-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_prescriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionhistory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
