# Generated by Django 6.0 on 2025-12-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_prescriptionhistory_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionhistory',
            name='notes',
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
